CREATE TABLE BOOK (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(150) NOT NULL,
    DESCRIPTION VARCHAR(255),
    PUBLISH_DATE DATE NOT NULL,
    AVAILABILITY VARCHAR(50) NOT NULL,
    IS_DELETED BOOLEAN NOT NULL
)