CREATE TABLE BOOK_AUTHORS (
  BOOK_ID INT NOT NULL,
  AUTHOR_ID INT NOT NULL,
  PRIMARY KEY (BOOK_ID, AUTHOR_ID),
  CONSTRAINT FK_BOOK
    FOREIGN KEY (BOOK_ID)
    REFERENCES BOOK (id)
    ON DELETE CASCADE,
  CONSTRAINT FK_AUTHOR
    FOREIGN KEY (AUTHOR_ID)
    REFERENCES AUTHOR (id)
    ON DELETE CASCADE
);

CREATE TABLE BOOK_CATEGORIES (
  BOOK_ID INT NOT NULL,
  CATEGORY_ID INT NOT NULL,
  PRIMARY KEY (BOOK_ID, CATEGORY_ID),
  CONSTRAINT FK_BOOK_CATEGORY
    FOREIGN KEY (BOOK_ID)
    REFERENCES BOOK (id)
    ON DELETE CASCADE,
  CONSTRAINT FK_CATEGORY
    FOREIGN KEY (CATEGORY_ID)
    REFERENCES CATEGORY (id)
    ON DELETE CASCADE
);